# config file

# ── paths ────────────────────────────────────────────────────────────────────
raw_data_path : 'C:\Users\narayana\projects\personal\arrhythmia_ml\data\raw'
models_path   : 'C:\Users\narayana\projects\personal\arrhythmia_ml\models'
features_path : 'C:\Users\narayana\projects\personal\arrhythmia_ml\features'
mlflow_exported: 'C:\Users\narayana\projects\personal\arrhythmia_ml\data\mlflow_exported'

# MLflow tracking URI — 'mlruns' folder will be created here locally.
# Change to a remote URI (e.g. http://localhost:5000) if you run a tracking server.
mlflow_tracking_uri: 'mlruns'

# MLflow experiment name — all runs will be grouped under this name in the UI.
mlflow_experiment_name: 'arrhythmia_beat_classification'

# ── signal processing params ──────────────────────────────────────────────────
general_bandpass: [0.5, 30.0]
notch: 50

beats_bandpass: [1, 15]
peak_calibration: 80   # ms window for calibrating detected peaks with annotated data

# ── feature extraction params ─────────────────────────────────────────────────
wfm_extraction_window: [-200, 400]   # ms before and after R peak
local_rr_mean_beat_window: 5
qrs_extraction_window: [-200, 60] # 200 ms before the r peak for Q and 60 ms after the peak for S


# ── model training params ─────────────────────────────────────────────────────
max_iter: 2000

# ── label filtering ───────────────────────────────────────────────────────────
# beat types to keep for classification — all others are discarded
keep_labels: ['N', 'A', 'V']

# ── experiments ───────────────────────────────────────────────────────────────
# Each experiment has:
#   run_name          : label shown in the MLflow UI
#   features          : list of feature groups to compute
#                       options -> "waves", "interval_related", "QRS" (waves is a strict requirement for computing QRS features)
#   classifier        : which model to use
#                       options -> "logreg", "gboost"
#   oversample        : whether you want to use SMOTE oversampling. beefs up training time.
#   classifier_params : optional dict of hyperparams passed to build_pipeline()
#                       logreg  keys -> max_iter, solver, verbose
#                       gboost  keys -> n_estimators, n_iter_no_change, validation_fraction
#   description       : free-text note logged as an MLflow tag
experiments:
  exp01_waves_logreg:
    run_name          : 'exp01_waves_logreg'
    features          : ['waves']
    classifier        : 'logreg'
    oversample        : False
    classifier_params : {max_iter: 2000, solver: 'saga', verbose: true}
    description       : 'Baseline — R waveforms only, logistic regression'

  exp02_waves_rr_logreg:
    run_name          : 'exp02_waves_rr_logreg'
    features          : ['waves', 'interval_related']
    classifier        : 'logreg'
    oversample        : False
    classifier_params : {max_iter: 2000, solver: 'saga', verbose: true}
    description       : 'R waveforms + RR interval features, logistic regression'

  exp03_waves_rr_gboost:
    run_name          : 'exp03_waves_rr_gboost'
    features          : ['waves', 'interval_related']
    classifier        : 'gboost'
    oversample        : False
    classifier_params : {n_estimators: 100, n_iter_no_change: 10, validation_fraction: 0.1}
    description       : 'R waveforms + RR interval features, gradient boosting'

  exp04_waves_rr_gboost_smote:
    run_name          : 'exp04_waves_rr_gboost_smote'
    features          : ['waves', 'interval_related']
    classifier        : 'gboost'
    oversample        : True
    classifier_params : {n_estimators: 100, n_iter_no_change: 10, validation_fraction: 0.1}
    description       : 'R waveforms + RR interval features, gradient boosting, oversampling'

  exp05_rr_gboost:
    run_name          : 'exp05_rr_gboost'
    features          : ['interval_related']
    classifier        : 'gboost'
    oversample        : False
    classifier_params : {n_estimators: 100, n_iter_no_change: 10, validation_fraction: 0.1}
    description       : 'RR interval features, gradient boosting, sample weight balanced'

  exp06_rr_gboost_smote:
    run_name          : 'exp06_rr_gboost_smote'
    features          : ['interval_related']
    classifier        : 'gboost'
    oversample        : True
    classifier_params : {n_estimators: 100, n_iter_no_change: 10, validation_fraction: 0.1}
    description       : 'RR interval features, gradient boosting, oversampling, sample weight balanced'

  exp07_waves_rr_QRS_gboost:
    run_name          : 'exp07_waves_rr_QRS_gboost'
    features          : ['waves','interval_related','QRS']
    classifier        : 'gboost'
    oversample        : False
    classifier_params : {n_estimators: 100, n_iter_no_change: 10, validation_fraction: 0.1}
    description       : 'Waves, RR interval features, gradient boosting, sample weight balanced'

  exp08_waves_rr_QRS_xgboost:
    run_name          : 'exp08_waves_rr_QRS_xgboost'
    features          : ['waves','interval_related','QRS']
    classifier        : 'xgboost'
    oversample        : False
    classifier_params : {n_estimators: 100, colsample_bylevel: 0.7, tree_method: 'hist', device: 'cpu'}
    description       : 'Waves, RR interval features, xtra gradient boosting, sample weight balanced'

